export const ADD_TO_CART_ITEM = "ADD_TO_CART_ITEM";
export const CART_INCREAGE = "CART_INCREAGE";
export const CART_DECREASE = "CART_DECREASE";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_EMPTY = "CART_EMPTY";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const WISHLIST_REMOVE_ITEM = "WISHLIST_REMOVE_ITEM";
