// ALL ADMIN
export const ALL_ADMIN_REQUEST = "ALL_ADMIN_REQUEST";
export const ALL_ADMIN_SUCCESS = "ALL_ADMIN_SUCCESS";
export const ALL_ADMIN_FAIL = "ALL_ADMIN_FAIL";
// ADMIN CREATE
export const ADMIN_CREATE_REQUEST = "ADMIN_CREATE_REQUEST";
export const ADMIN_CREATE_SUCCESS = "ADMIN_CREATE_SUCCESS";
export const ADMIN_CREATE_FAIL = "ADMIN_CREATE_FAIL";
export const ADMIN_CREATE_RESET = "ADMIN_CREATE_RESET";
// ADMIN DETAILS
export const ADMIN_DETAILS_REQUEST = "ADMIN_DETAILS_REQUEST";
export const ADMIN_DETAILS_SUCCESS = "ADMIN_DETAILS_SUCCESS";
export const ADMIN_DETAILS_FAIL = "ADMIN_DETAILS_FAIL";
// ADMIN UPDATE
export const ADMIN_UPDATE_REQUEST = "ADMIN_UPDATE_REQUEST";
export const ADMIN_UPDATE_SUCCESS = "ADMIN_UPDATE_SUCCESS";
export const ADMIN_UPDATE_FAIL = "ADMIN_UPDATE_FAIL";
export const ADMIN_UPDATE_RESET = "ADMIN_UPDATE_RESET";
// ADMIN DELETE
export const ADMIN_DELETE_REQUEST = "ADMIN_DELETE_REQUEST";
export const ADMIN_DELETE_SUCCESS = "ADMIN_DELETE_SUCCESS";
export const ADMIN_DELETE_FAIL = "ADMIN_DELETE_FAIL";
export const ADMIN_DELETE_RESET = "ADMIN_DELETE_RESET";
// ADMIN SIGNIN
export const ADMIN_SIGNIN_REQUEST = "ADMIN_SIGNIN_REQUEST";
export const ADMIN_SIGNIN_SUCCESS = "ADMIN_SIGNIN_SUCCESS";
export const ADMIN_SIGNIN_FAIL = "ADMIN_SIGNIN_FAIL";
export const ADMIN_SIGNIN_RESET = "ADMIN_SIGNIN_RESET";
// ADMIN LOGOUT
export const ADMIN_SIGNOUT = "ADMIN_SIGNOUT";
