// ALL BANNER
export const ALL_BANNER_REQUEST = "ALL_BANNER_REQUEST";
export const ALL_BANNER_SUCCESS = "ALL_BANNER_SUCCESS";
export const ALL_BANNER_FAIL = "ALL_BANNER_FAIL";
// BANNER CREATE
export const BANNER_CREATE_REQUEST = "BANNER_CREATE_REQUEST";
export const BANNER_CREATE_SUCCESS = "BANNER_CREATE_SUCCESS";
export const BANNER_CREATE_FAIL = "BANNER_CREATE_FAIL";
export const BANNER_CREATE_RESET = "BANNER_CREATE_RESET";
// BANNER DETAILS
export const BANNER_DETAILS_REQUEST = "BANNER_DETAILS_REQUEST";
export const BANNER_DETAILS_SUCCESS = "BANNER_DETAILS_SUCCESS";
export const BANNER_DETAILS_FAIL = "BANNER_DETAILS_FAIL";
// BANNER UPDATE
export const BANNER_UPDATE_REQUEST = "BANNER_UPDATE_REQUEST";
export const BANNER_UPDATE_SUCCESS = "BANNER_UPDATE_SUCCESS";
export const BANNER_UPDATE_FAIL = "BANNER_UPDATE_FAIL";
export const BANNER_UPDATE_RESET = "BANNER_UPDATE_RESET";
// BANNER DELETE
export const BANNER_DELETE_REQUEST = "BANNER_DELETE_REQUEST";
export const BANNER_DELETE_SUCCESS = "BANNER_DELETE_SUCCESS";
export const BANNER_DELETE_FAIL = "BANNER_DELETE_FAIL";
export const BANNER_DELETE_RESET = "BANNER_DELETE_RESET";
