export const ADD_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";

export const GET_HOMECATEGORY_REQUEST = "GET_HOMECATEGORY_REQUEST";
export const GET_HOMECATEGORY_SUCCESS = "GET_HOMECATEGORY_SUCCESS";
export const GET_HOMECATEGORY_FAIL = "GET_HOMECATEGORY_FAIL";

export const CATEGORY_DETAILS_REQUEST = "CATEGORY_DETAILS_REQUEST";
export const CATEGORY_DETAILS_SUCCESS = "CATEGORY_DETAILS_SUCCESS";
export const CATEGORY_DETAILS_FAIL = "CATEGORY_DETAILS_FAIL";
export const CATEGORY_DETAILS_RESET = "CATEGORY_DETAILS_RESET";

export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAIL = "CATEGORY_CREATE_FAIL";
export const CATEGORY_CREATE_RESET = "CATEGORY_CREATE_RESET";

export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_FAIL";
export const CATEGORY_DELETE_RESET = "CATEGORY_DELETE_RESET";

export const CATEGORY_UPDATE_REQUEST = "CATEGORY_UPDATE_REQUEST";
export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAIL = "CATEGORY_UPDATE_FAIL";
export const CATEGORY_UPDATE_RESET = "CATEGORY_UPDATE_RESET";

export const CATEGORY_CHILDATA_REQUEST = "CATEGORY_CHILDATA_REQUEST";
export const CATEGORY_CHILDATA_SUCCESS = "CATEGORY_CHILDATA_SUCCESS";
export const CATEGORY_CHILDATA_FAIL = "CATEGORY_CHILDATA_FAIL";
export const CATEGORY_CHILDATA_RESET = "CATEGORY_CHILDATA_RESET";

export const SUB_CATEGORY_CHILDATA_REQUEST = "SUB_CATEGORY_CHILDATA_REQUEST";
export const SUB_CATEGORY_CHILDATA_SUCCESS = "SUB_CATEGORY_CHILDATA_SUCCESS";
export const SUB_CATEGORY_CHILDATA_FAIL = "SUB_CATEGORY_CHILDATA_FAIL";
export const SUB_CATEGORY_CHILDATA_RESET = "SUB_CATEGORY_CHILDATA_RESET";
