export const CONVERSATION_BYID_REQUEST = "CONVERSATION_BYID_REQUEST";
export const CONVERSATION_BYID_SUCCESS = "CONVERSATION_BYID_SUCCESS";
export const CONVERSATION_BYID_FAIL = "CONVERSATION_BYID_FAIL";

export const CREATE_CONVERSATION_REQUEST = "CREATE_CONVERSATION_REQUEST";
export const CREATE_CONVERSATION_SUCCESS = "CREATE_CONVERSATION_SUCCESS";
export const CREATE_CONVERSATION_FAIL = "CREATE_CONVERSATION_FAIL";
export const CREATE_CONVERSATION_RESET = "CREATE_CONVERSATION_RESET";

export const GET_MESSAGES_BY_CONVERSATION_ID_REQUEST =
  "GET_MESSAGES_BY_CONVERSATION_ID_REQUEST";

export const GET_MESSAGES_BY_CONVERSATION_ID_SUCCESS =
  "GET_MESSAGES_BY_CONVERSATION_ID_SUCCESS";

export const GET_MESSAGES_BY_CONVERSATION_ID_FAIL =
  "GET_MESSAGES_BY_CONVERSATION_ID_FAIL";
