export const All_CONTACT_US_REQUEST = "All_CONTACT_US_REQUEST";
export const All_CONTACT_US_SUCCESS = "All_CONTACT_US_SUCCESS";
export const All_CONTACT_US_FAIL = "All_CONTACT_US_FAIL";

export const CONTACT_US_CREATE_REQUEST = "CONTACT_US_CREATE_REQUEST";
export const CONTACT_US_CREATE_SUCCESS = "CONTACT_US_CREATE_SUCCESS";
export const CONTACT_US_CREATE_FAIL = "CONTACT_US_CREATE_FAIL";
export const CONTACT_US_CREATE_RESET = "CONTACT_US_CREATE_RESET";

export const CONTACT_US_DETAILS_REQUEST = "CONTACT_US_DETAILS_REQUEST";
export const CONTACT_US_DETAILS_SUCCESS = "CONTACT_US_DETAILS_SUCCESS";
export const CONTACT_US_DETAILS_FAIL = "CONTACT_US_DETAILS_FAIL";

export const CONTACT_US_UPDATE_REQUEST = "CONTACT_US_UPDATE_REQUEST";
export const CONTACT_US_UPDATE_SUCCESS = "CONTACT_US_UPDATE_SUCCESS";
export const CONTACT_US_UPDATE_FAIL = "CONTACT_US_UPDATE_FAIL";
export const CONTACT_US_UPDATE_RESET = "CONTACT_US_UPDATE_RESET";

export const CONTACT_US_DELETE_REQUEST = "CONTACT_US_DELETE_REQUEST";
export const CONTACT_US_DELETE_SUCCESS = "CONTACT_US_DELETE_SUCCESS";
export const CONTACT_US_DELETE_FAIL = "CONTACT_US_DELETE_FAIL";
export const CONTACT_US_DELETE_RESET = "CONTACT_US_DELETE_RESET";
