// all entrepreneurs list
export const ALL_ENTREPRENEURS_REQUEST = "ALL_ENTREPRENEURS_REQUEST";
export const ALL_ENTREPRENEURS_SUCCESS = "ALL_ENTREPRENEURS_SUCCESS";
export const ALL_ENTREPRENEURS_FAIL = "ALL_ENTREPRENEURS_FAIL";

// entrepreneurs create
export const ENTREPRENEURS_CREATE_REQUEST = "ENTREPRENEURS_CREATE_REQUEST";
export const ENTREPRENEURS_CREATE_SUCCESS = "ENTREPRENEURS_CREATE_SUCCESS";
export const ENTREPRENEURS_CREATE_FAIL = "ENTREPRENEURS_CREATE_FAIL";
export const ENTREPRENEURS_CREATE_RESET = "ENTREPRENEURS_CREATE_RESET";

// entrepreneurs edit
export const ENTREPRENEURS_EDIT_REQUEST = "ENTREPRENEURS_EDIT_REQUEST";
export const ENTREPRENEURS_EDIT_SUCCESS = "ENTREPRENEURS_EDIT_SUCCESS";
export const ENTREPRENEURS_EDIT_FAIL = "ENTREPRENEURS_EDIT_FAIL";

// entrepreneurs delete
export const ENTREPRENEURS_DELETE_REQUEST = "ENTREPRENEURS_DELETE_REQUEST";
export const ENTREPRENEURS_DELETE_SUCCESS = "ENTREPRENEURS_DELETE_SUCCESS";
export const ENTREPRENEURS_DELETE_FAIL = "ENTREPRENEURS_DELETE_FAIL";
export const ENTREPRENEURS_DELETE_RESET = "ENTREPRENEURS_DELETE_RESET";

// entrepreneurs update
export const ENTREPRENEURS_UPDATE_REQUEST = "ENTREPRENEURS_UPDATE_REQUEST";
export const ENTREPRENEURS_UPDATE_SUCCESS = "ENTREPRENEURS_UPDATE_SUCCESS";
export const ENTREPRENEURS_UPDATE_FAIL = "ENTREPRENEURS_UPDATE_FAIL";
export const ENTREPRENEURS_UPDATE_RESET = "ENTREPRENEURS_UPDATE_RESET";

//image uploading
export const ENTREPRENEURS_IMAGEUPLOAD_REQUEST =
  "ENTREPRENEURS_IMAGEUPLOAD_REQUEST";
export const ENTREPRENEURS_IMAGEUPLOAD_SUCCESS =
  "ENTREPRENEURS_IMAGEUPLOAD_SUCCESS";
export const ENTREPRENEURS_IMAGEUPLOAD_FAIL = "ENTREPRENEURS_IMAGEUPLOAD_FAIL";
