export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_RESET = "PRODUCT_DETAILS_RESET";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET";

export const PRODUCT_WISHLISTADD_REQUEST = "PRODUCT_WISHLISTADD_REQUEST";
export const PRODUCT_WISHLISTADD_SUCCESS = "PRODUCT_WISHLISTADD_SUCCESS";
export const PRODUCT_WISHLISTADD_FAIL = "PRODUCT_WISHLISTADD_FAIL";
export const PRODUCT_WISHLISTADD_RESET = "PRODUCT_WISHLISTADD_RESET";

export const PRODUCT_WISHLISTREMOVE_REQUEST = "PRODUCT_WISHLISTREMOVE_REQUEST";
export const PRODUCT_WISHLISTREMOVE_SUCCESS = "PRODUCT_WISHLISTREMOVE_SUCCESS";
export const PRODUCT_WISHLISTREMOVE_FAIL = "PRODUCT_WISHLISTREMOVE_FAIL";
export const PRODUCT_WISHLISTREMOVE_RESET = "PRODUCT_WISHLISTREMOVE_RESET";

export const PRODUCT_REVIEW_CREATE_REQUEST = "PRODUCT_REVIEW_CREATE_REQUEST";
export const PRODUCT_REVIEW_CREATE_SUCCESS = "PRODUCT_REVIEW_CREATE_SUCCESS";
export const PRODUCT_REVIEW_CREATE_FAIL = "PRODUCT_REVIEW_CREATE_FAIL";
export const PRODUCT_REVIEW_CREATE_RESET = "PRODUCT_REVIEW_CREATE_RESET";

export const PRODUCT_QNA_CREATE_REQUEST = "PRODUCT_QNA_CREATE_REQUEST";
export const PRODUCT_QNA_CREATE_SUCCESS = "PRODUCT_QNA_CREATE_SUCCESS";
export const PRODUCT_QNA_CREATE_FAIL = "PRODUCT_QNA_CREATE_FAIL";
export const PRODUCT_QNA_CREATE_RESET = "PRODUCT_QNA_CREATE_RESET";

export const PRODUCT_SAVE_DATA = "PRODUCT_SAVE_DATA";

// home page product category constant
export const HOME_PAGE_PRODUCT_CATEGORY_DATA_REQUEST =
  "HOME_PAGE_PRODUCT_CATEGORY_DATA_REQUEST";
export const HOME_PAGE_PRODUCT_CATEGORY_DATA_SUCCESS =
  "HOME_PAGE_PRODUCT_CATEGORY_DATA_SUCCESS";
export const HOME_PAGE_PRODUCT_CATEGORY_DATA_FAIL =
  "HOME_PAGE_PRODUCT_CATEGORY_DATA_FAIL";

// home page product feature constant
export const HOME_PAGE_PRODUCT_FEATURE_DATA_REQUEST =
  "HOME_PAGE_PRODUCT_CATEGORY_DATA_REQUEST";
export const HOME_PAGE_PRODUCT_FEATURE_DATA_SUCCESS =
  "HOME_PAGE_PRODUCT_CATEGORY_DATA_SUCCESS";
export const HOME_PAGE_PRODUCT_FEATURE_DATA_FAIL =
  "HOME_PAGE_PRODUCT_CATEGORY_DATA_FAIL";
