// all size
export const ALL_SIZE_REQUEST = "ALL_SIZE_REQUEST";
export const ALL_SIZE_SUCCESS = "ALL_SIZE_SUCCESS";
export const ALL_SIZE_FAIL = "ALL_SIZE_FAIL";
// size create
export const SIZE_CREATE_REQUEST = "SIZE_CREATE_REQUEST";
export const SIZE_CREATE_SUCCESS = "SIZE_CREATE_SUCCESS";
export const SIZE_CREATE_FAIL = "SIZE_CREATE_FAIL";
export const SIZE_CREATE_RESET = "SIZE_CREATE_RESET";
// size edit
export const SIZE_EDIT_REQUEST = "SIZE_EDIT_REQUEST";
export const SIZE_EDIT_SUCCESS = "SIZE_EDIT_SUCCESS";
export const SIZE_EDIT_FAIL = "SIZE_EDIT_FAIL";
// size delete
export const SIZE_DELETE_REQUEST = "SIZE_DELETE_REQUEST";
export const SIZE_DELETE_SUCCESS = "SIZE_DELETE_SUCCESS";
export const SIZE_DELETE_FAIL = "SIZE_DELETE_FAIL";
export const SIZE_DELETE_RESET = "SIZE_DELETE_RESET";
// size update
export const SIZE_UPDATE_REQUEST = "SIZE_UPDATE_REQUEST";
export const SIZE_UPDATE_SUCCESS = "SIZE_UPDATE_SUCCESS";
export const SIZE_UPDATE_FAIL = "SIZE_UPDATE_FAIL";
export const SIZE_UPDATE_RESET = "SIZE_UPDATE_RESET";
