// all SUPPORT TICKETS
export const ALL_SUPPORT_TICKETS_REQUEST = "ALL_SUPPORT_TICKETS_REQUEST";
export const ALL_SUPPORT_TICKETS_SUCCESS = "ALL_SUPPORT_TICKETS_SUCCESS";
export const ALL_SUPPORT_TICKETS_FAIL = "ALL_SUPPORT_TICKETS_FAIL";
// SUPPORT TICKETS create
export const SUPPORT_TICKETS_CREATE_REQUEST = "SUPPORT_TICKETS_CREATE_REQUEST";
export const SUPPORT_TICKETS_CREATE_SUCCESS = "SUPPORT_TICKETS_CREATE_SUCCESS";
export const SUPPORT_TICKETS_CREATE_FAIL = "SUPPORT_TICKETS_CREATE_FAIL";
export const SUPPORT_TICKETS_CREATE_RESET = "SUPPORT_TICKETS_CREATE_RESET";
// SUPPORT TICKETS DETAILS
export const SUPPORT_TICKETS_DETAILS_REQUEST =
  "SUPPORT_TICKETS_DETAILS_REQUEST";
export const SUPPORT_TICKETS_DETAILS_SUCCESS =
  "SUPPORT_TICKETS_DETAILS_SUCCESS";
export const SUPPORT_TICKETS_DETAILS_FAIL = "SUPPORT_TICKETS_DETAILS_FAIL";
// SUPPORT TICKETS update
export const SUPPORT_TICKETS_UPDATE_REQUEST = "SUPPORT_TICKETS_UPDATE_REQUEST";
export const SUPPORT_TICKETS_UPDATE_SUCCESS = "SUPPORT_TICKETS_UPDATE_SUCCESS";
export const SUPPORT_TICKETS_UPDATE_FAIL = "SUPPORT_TICKETS_UPDATE_FAIL";
export const SUPPORT_TICKETS_UPDATE_RESET = "SUPPORT_TICKETS_UPDATE_RESET";
//SUPPORT TICKET RECOMMENT
export const SUPPORT_TICKETS_RECOMMENT_REQUEST =
  "SUPPORT_TICKETS_RECOMMENT_REQUEST";
export const SUPPORT_TICKETS_RECOMMENT_SUCCESS =
  "SUPPORT_TICKETS_RECOMMENT_SUCCESS";
export const SUPPORT_TICKETS_RECOMMENT_FAIL = "SUPPORT_TICKETS_RECOMMENT_FAIL";
export const SUPPORT_TICKETS_RECOMMENT_RESET =
  "SUPPORT_TICKETS_RECOMMENT_RESET";

//SUPPORT TICKET ADMIN REPLAY
export const SUPPORT_TICKETS_ADMIN_REQUEST = "SUPPORT_TICKETS_ADMIN_REQUEST";
export const SUPPORT_TICKETS_ADMIN_SUCCESS = "SUPPORT_TICKETS_ADMIN_SUCCESS";
export const SUPPORT_TICKETS_ADMIN_FAIL = "SUPPORT_TICKETS_ADMIN_FAIL";
export const SUPPORT_TICKETS_ADMIN_RESET = "SUPPORT_TICKETS_ADMIN_RESET";

// SUPPORT TICKETS delete
export const SUPPORT_TICKETS_DELETE_REQUEST = "SUPPORT_TICKETS_DELETE_REQUEST";
export const SUPPORT_TICKETS_DELETE_SUCCESS = "SUPPORT_TICKETS_DELETE_SUCCESS";
export const SUPPORT_TICKETS_DELETE_FAIL = "SUPPORT_TICKETS_DELETE_FAIL";
export const SUPPORT_TICKETS_DELETE_RESET = "SUPPORT_TICKETS_DELETE_RESET";
