// user register
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

// register with google
export const GOOGLE_REGISTER_REQUEST = "GOOGLE_REGISTER_REQUEST";
export const GOOGLE_REGISTER_SUCCESS = "GOOGLE_REGISTER_SUCCESS";
export const GOOGLE_REGISTER_FAIL = "GOOGLE_REGISTER_FAIL";
export const GOOGLE_REGISTER_RESET = "GOOGLE_REGISTER_RESET";

// user signin
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET";

// signin with google
export const GOOGLE_SIGNIN_REQUEST = "GOOGLE_SIGNIN_REQUEST";
export const GOOGLE_SIGNIN_SUCCESS = "GOOGLE_SIGNIN_SUCCESS";
export const GOOGLE_SIGNIN_FAIL = "GOOGLE_SIGNIN_FAIL";
export const GOOGLE_SIGNIN_RESET = "GOOGLE_SIGNIN_RESET";

// user logout
export const USER_SIGNOUT = "USER_SIGNOUT";

//google user logout
export const GOOGLE_SIGNOUT = "GOOGLE_SIGNOUT";

//  user list
export const ALL_USER_REQUEST = "ALL_USER_REQUEST";
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS";
export const ALL_USER_FAIL = "ALL_USER_FAIL";

// google user list
export const ALL_GOOGLE_USER_REQUEST = "ALL_GOOGLE_USER_REQUEST";
export const ALL_GOOGLE_USER_SUCCESS = "ALL_GOOGLE_USER_SUCCESS";
export const ALL_GOOGLE_USER_FAIL = "ALL_GOOGLE_USER_FAIL";

// user single
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

//google user single
export const GOOGLE_USER_DETAILS_REQUEST = "GOOGLE_USER_DETAILS_REQUEST";
export const GOOGLE_USER_DETAILS_SUCCESS = "GOOGLE_USER_DETAILS_SUCCESS";
export const GOOGLE_USER_DETAILS_FAIL = "GOOGLE_USER_DETAILS_FAIL";
export const GOOGLE_USER_DETAILS_RESET = "GOOGLE_USER_DETAILS_RESET";

// user delete
export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_RESET = "USER_DELETE_RESET";
// user update
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";
